name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      # JSON must be a single-line string. Override these in your CI if you need
      # different thresholds for the job.
      PERFORMANCE_THRESHOLDS: '{"goodAvgFPS":55,"fairAvgFPS":30,"poorAvgFrameTime":33,"worstFrameTime":60,"memoryGrowthBytes":52428800}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run rendering BDD tests
        run: npm run test:rendering-bdd
