declare function createVector(x?: number, y?: number, z?: number): { x: number; y: number; z?: number; };
declare function push(): void;
declare function pop(): void;
declare function strokeWeight(n: number): void;
declare function stroke(r: number, g?: number, b?: number): void;
declare function noStroke(): void;
declare function fill(r: number, g?: number, b?: number): void;
declare function noFill(): void;
declare function rect(x: number, y: number, w: number, h: number): void;
declare function keyIsDown(key: number): boolean;